### ISSUE TITLE
Error in duration test

### ISSUE THREAD

**Issue by RuichengGeng** [rafa-rod/vartests#1]
Hi there,

Thanks a lot for this open source var tests algos!
I found an error occurred when running duration test(Christofferson duration test).
When I input a violations series starting with 1, the error reported: UnboundLocalError: local variable 'D' referenced before assignment.
From the code, we could also find that when violation series start with 1, D is unassigned.
![image](https://user-images.githubusercontent.com/48621842/185090260-0e348d84-c8e8-4fac-8301-32ddcfb91cb1.png)
I might have a bug free algo in creating durations and censor series, welcome to discuss with me if you want :).
Also, I have another question about the optimization part, where you assign: N = len(D)-1, I guess you do minus 1 to make the index correct. But based on the Christofferson paper, it should be N = len(D) from my point of view.

Best regards,
Ruicheng

**Comment by RuichengGeng** [comment]
@rafa-rod

**Comment by rafa-rod** [comment]
Hi Ruicheng, how are you?

I had already noticed that in some cases the duration test returned errors. I haven't had time to study the case yet. Feel free to suggest changes. As soon as I have a little free time here, I'm going to look more deeply into this case.

About the optimization part, I also will review Christofferson's paper.

Best Regards,
Rafael.

**Comment by rafa-rod** [comment]
Hi Ruicheng, how are you?

I had already noticed that in some cases the duration test returned errors.
I haven't had time to study the case yet. Feel free to suggest changes. As
soon as I have a little free time here, I'm going to look more deeply into
this case.

About the optimization part, I also will review Christofferson's paper.

Best Regards,
Rafael.

Em qua., 17 de ago. de 2022 às 07:06, Ruicheng Geng <
***@***.***> escreveu:

**Comment by RuichengGeng** [comment]
Hi Rafael,

Thanks a lot for you response!
Here is my idea: since length of D(durations) and C(censor series) has the same length and only C[0] and C[-1] counts, so we can generate C series after constructing D and change C[0] and C[-1].
This is my change:
```
    TN = len(violations)
   # change start from here
    if not duration:
        return
    
    if first_hit == 0:
        D = np.append(duration[0], diff_duration) #days until first violation
    else:
        D = diff_duration.copy()
        
    if last_hit==0:
        D = np.append(D, TN-duration[-1]-1)

    C = np.zeros(len(D))
    C[0] = not first_hit
    C[-1] = not last_hit
     # end here
    if N>0 and duration: N = len(D)-1
    else: N=0

   
```

Feel free to discuss with me if you have any questions,

Best regards,
Ruicheng

**Comment by rafa-rod** [comment]
Hi Ruicheng,

I looked deep this problem and I realized that UnboundLocalError occurred when you pass a List or Array. I fixed the function to accept that kinds of inputs and I added typing in all functions to clarify that.

About N = len(D)-1 issue, its because the function likDurationW uses C[N], which means that it want to take the last value of the array C, but in python the first one is zero (C[0]) and the last one is not C[N], but C[N-1]. So its correct.

I added a test directory if we want to test the duration function.

Best Regards,
Rafael.

**Comment by RuichengGeng** [comment]
Hi Rafael,

Thank you so much for you investigation and adding a unit test!
Here is my finding based on your latest implementation:
1.  unit test failed occassionaly, it is because the violation series starting with 1 happened randomly, when start with 1 it fails.
2. pd.DataFrame should not be supported. As in `duration = [i for i, x in enumerate(violations) if x == 1]`, it just iterate over columns and finally produce an empty list. That's also why some unit test passed.
3. About the N = len(D)-1 issue, I understand that you do -1 to make index correct. But based on paper, in likelihood function optimization part : `a = ((N - C[0] - C[N]) / (sum(D ** b))) ** (1 / b)`, here N should b len(D) instead of len(D) - 1.

Could you please give me access to this repo such that I can pull my branch to make it easy for us to discuss?

Best regards,
Ruicheng

**Comment by RuichengGeng** [comment]
I have created a branch in my fork, please refer to: 

> RuichengGeng:branch-ruicheng

**Comment by RuichengGeng** [comment]
I have pulled a branch in my fork, please refer to:
please refer to : [https://github.com/RuichengGeng/vartests/tree/branch-ruicheng](url)

**Comment by rafa-rod** [comment]
Ruicheng,

I have accepted your request, however still there were a lot of bugs in boundary conditions. I have fixed all of them and also have added unit tests.

Best regards,
Rafael

**Comment by RuichengGeng** [comment]
Hi Rafeal,

Thank you so much for spending weekend on this issue, now the duration tests runs perfectly well:)
I left one comment in pytest part, you can take a look when you are free.
Very happy working together with you on this issue!

Best regards,
Ruicheng
